# adapters/opencode/adapter.ps1 - OpenCode platform adapter
# Dot-sourced by scripts/build.ps1 after adapters/lib.ps1.

$OPENCODE_PLATFORM   = "opencode"
$OPENCODE_DIR        = "opencode"
$OPENCODE_DISPATCHER = "AGENTS.md"

function adapter_build {
    param([string]$Src, [string]$Dst)
    _OpenCode-EmitDispatcher    $Src $Dst
    _OpenCode-TranslateCommands (Join-Path $Src 'commands')   (Join-Path $Dst ".$OPENCODE_DIR\commands")
    _OpenCode-CopyReferences    (Join-Path $Src 'references') (Join-Path $Dst ".$OPENCODE_DIR\references")
    _OpenCode-CopyScripts       (Join-Path $Src 'scripts')    (Join-Path $Dst ".$OPENCODE_DIR\scripts")
    _OpenCode-EmitInstallHint   $Dst
}

function _OpenCode-EmitDispatcher {
    param([string]$Src, [string]$Dst)
    $out      = Join-Path $Dst $OPENCODE_DISPATCHER
    $routing  = Emit-RoutingTableGrouped (Join-Path $Src 'commands') $OPENCODE_PLATFORM ".opencode/commands"
    $triggers = Emit-TriggerReference   (Join-Path $Src 'commands') $OPENCODE_PLATFORM
    $content = @'
# Obsidian Second Brain - OpenCode Operating Manual

This vault runs the **obsidian-second-brain** skill. The skill ships a set of
*commands*: each one is a multi-step instruction file that you (the OpenCode
agent) should follow when the user's request matches its trigger phrase.

## How to operate

1. Read `_CLAUDE.md` in the vault root, if it exists, to learn the user's
   vault conventions.
2. When the user's request matches a trigger in the tables below, read the
   matching file under `.opencode/commands/<name>.md` and follow its
   instructions step by step.
3. Treat the AI-first vault rule (`references/ai-first-rules.md`) as
   non-negotiable for every note you write: `## For future Claude` preamble,
   rich frontmatter (`type`, `date`, `tags`, `ai-first: true`), `[[wikilinks]]`
   for every person/project/concept, recency markers per external claim,
   sources verbatim, confidence levels where applicable.

## Command routing tables (grouped by category)
'@
    $content += $routing + $triggers
    $content += @'

---

*Generated by adapters/opencode/adapter.ps1 - do not edit manually.*
'@
    [System.IO.File]::WriteAllText($out, $content, [System.Text.Encoding]::UTF8)
}

function _OpenCode-TranslateCommands {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    foreach ($f in (Get-ChildItem $Src -Filter "*.md")) {
        if (-not (Should-Include $f.FullName $OPENCODE_PLATFORM)) { continue }
        $out = Join-Path $Dst $f.Name
        Copy-Item $f.FullName $out
        Rewrite-ToolNeutral   $out
        Rewrite-PlatformPaths $out $OPENCODE_DIR
    }
}

function _OpenCode-CopyReferences {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    Copy-Item "$Src\*" $Dst -Recurse -Force
    foreach ($f in (Get-ChildItem $Dst -Filter "*.md" -Recurse)) {
        Rewrite-PlatformPaths $f.FullName $OPENCODE_DIR
    }
}

function _OpenCode-CopyScripts {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    Copy-Item "$Src\*" $Dst -Recurse -Force
}

function _OpenCode-EmitInstallHint {
    param([string]$Dst)
    $content = @'
# Install on OpenCode

```powershell
# After running: pwsh -File scripts/build.ps1 --platform opencode
Copy-Item "dist\opencode\*" "/path/to/your/vault/" -Recurse -Force
```

Then in your vault:

- `AGENTS.md` is the operating manual OpenCode reads at session start.
- `.opencode/commands/*.md` are the command bodies the AI follows.
- `.opencode/scripts/` holds the Python helpers.
'@
    [System.IO.File]::WriteAllText((Join-Path $Dst 'INSTALL.md'), $content, [System.Text.Encoding]::UTF8)
}
