# adapters/gemini-cli/adapter.ps1 - Gemini CLI platform adapter
# Dot-sourced by scripts/build.ps1 after adapters/lib.ps1.

$GEMINI_PLATFORM   = "gemini-cli"
$GEMINI_DIR        = "gemini"
$GEMINI_DISPATCHER = "GEMINI.md"

function adapter_build {
    param([string]$Src, [string]$Dst)
    _Gemini-EmitDispatcher    $Src $Dst
    _Gemini-TranslateCommands (Join-Path $Src 'commands')   (Join-Path $Dst ".$GEMINI_DIR\commands")
    _Gemini-CopyReferences    (Join-Path $Src 'references') (Join-Path $Dst ".$GEMINI_DIR\references")
    _Gemini-CopyScripts       (Join-Path $Src 'scripts')    (Join-Path $Dst ".$GEMINI_DIR\scripts")
    _Gemini-EmitInstallHint   $Dst
}

function _Gemini-EmitDispatcher {
    param([string]$Src, [string]$Dst)
    $out      = Join-Path $Dst $GEMINI_DISPATCHER
    $routing  = Emit-RoutingTableGrouped (Join-Path $Src 'commands') $GEMINI_PLATFORM ".gemini/commands"
    $triggers = Emit-TriggerReference   (Join-Path $Src 'commands') $GEMINI_PLATFORM
    $content = @'
# Obsidian Second Brain - Gemini CLI Operating Manual

This vault runs the **obsidian-second-brain** skill. The skill ships a set of
*commands*: each one is a multi-step instruction file that you (the Gemini
agent) should follow when the user's request matches its trigger phrase.

## How to operate

1. Read `_CLAUDE.md` in the vault root, if it exists, to learn the user's
   vault conventions.
2. When the user's request matches a trigger in the tables below, read the
   matching file under `.gemini/commands/<name>.md` and follow its
   instructions step by step.
3. Treat the AI-first vault rule (`references/ai-first-rules.md`) as
   non-negotiable for every note you write: `## For future Claude` preamble,
   rich frontmatter (`type`, `date`, `tags`, `ai-first: true`), `[[wikilinks]]`
   for every person/project/concept, recency markers per external claim,
   sources verbatim, confidence levels where applicable.

## Command routing tables (grouped by category)
'@
    $content += $routing + $triggers
    $content += @'

---

*Generated by adapters/gemini-cli/adapter.ps1 - do not edit manually.*
'@
    [System.IO.File]::WriteAllText($out, $content, [System.Text.Encoding]::UTF8)
}

function _Gemini-TranslateCommands {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    foreach ($f in (Get-ChildItem $Src -Filter "*.md")) {
        if (-not (Should-Include $f.FullName $GEMINI_PLATFORM)) { continue }
        $out = Join-Path $Dst $f.Name
        Copy-Item $f.FullName $out
        Rewrite-ToolNeutral   $out
        Rewrite-PlatformPaths $out $GEMINI_DIR
    }
}

function _Gemini-CopyReferences {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    Copy-Item "$Src\*" $Dst -Recurse -Force
    foreach ($f in (Get-ChildItem $Dst -Filter "*.md" -Recurse)) {
        Rewrite-PlatformPaths $f.FullName $GEMINI_DIR
    }
}

function _Gemini-CopyScripts {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    Copy-Item "$Src\*" $Dst -Recurse -Force
}

function _Gemini-EmitInstallHint {
    param([string]$Dst)
    $content = @'
# Install on Gemini CLI

```powershell
# After running: pwsh -File scripts/build.ps1 --platform gemini-cli
Copy-Item "dist\gemini-cli\*" "/path/to/your/vault/" -Recurse -Force
```

Then in your vault:

- `GEMINI.md` is the operating manual Gemini reads at session start.
- `.gemini/commands/*.md` are the command bodies the AI follows.
- `.gemini/scripts/` holds the Python helpers (`uv run -m scripts.research.<name>`).
'@
    [System.IO.File]::WriteAllText((Join-Path $Dst 'INSTALL.md'), $content, [System.Text.Encoding]::UTF8)
}
