# adapters/codex-cli/adapter.ps1 - OpenAI Codex CLI platform adapter
# Dot-sourced by scripts/build.ps1 after adapters/lib.ps1.

$CODEX_PLATFORM   = "codex-cli"
$CODEX_DIR        = "codex"
$CODEX_DISPATCHER = "AGENTS.md"

function adapter_build {
    param([string]$Src, [string]$Dst)
    _Codex-EmitDispatcher    $Src $Dst
    _Codex-TranslateCommands (Join-Path $Src 'commands')   (Join-Path $Dst ".$CODEX_DIR\commands")
    _Codex-CopyReferences    (Join-Path $Src 'references') (Join-Path $Dst ".$CODEX_DIR\references")
    _Codex-CopyScripts       (Join-Path $Src 'scripts')    (Join-Path $Dst ".$CODEX_DIR\scripts")
    _Codex-EmitInstallHint   $Dst
}

function _Codex-EmitDispatcher {
    param([string]$Src, [string]$Dst)
    $out     = Join-Path $Dst $CODEX_DISPATCHER
    $routing = Emit-RoutingTableGrouped (Join-Path $Src 'commands') $CODEX_PLATFORM ".codex/commands"
    $triggers = Emit-TriggerReference  (Join-Path $Src 'commands') $CODEX_PLATFORM
    $content = @'
# Obsidian Second Brain - Codex CLI Operating Manual

This vault runs the **obsidian-second-brain** skill. The skill ships a set of
*commands*: each one is a multi-step instruction file that you (the Codex
agent) should follow when the user's request matches its trigger phrase.

## How to operate

1. Read `_CLAUDE.md` in the vault root, if it exists, to learn the user's
   vault conventions (folder map, daily note format, naming).
2. When the user's request matches a trigger in the tables below, read the
   matching file under `.codex/commands/<name>.md` and follow its
   instructions step by step.
3. Treat the AI-first vault rule (`references/ai-first-rules.md`) as
   non-negotiable for every note you write: `## For future Claude` preamble,
   rich frontmatter (`type`, `date`, `tags`, `ai-first: true`), `[[wikilinks]]`
   for every person/project/concept, recency markers per external claim,
   sources verbatim, confidence levels where applicable.
4. Do not invent commands. If no command matches, ask the user what they
   want or fall back to plain natural-language help.

## Command routing tables (grouped by category)
'@
    $content += $routing + $triggers
    $content += @'

## Trigger conventions

Each command file has a leading paragraph that documents its trigger phrases
in plain English. Treat those triggers as primary; the slash-form `/name` is
also accepted if the user types it.

## Scripts

Python helpers live under `.codex/scripts/`. They run via `uv run -m
scripts.research.<name>` from the vault root (or wherever the skill is
installed). The commands that need them reference the exact invocation
inside the command body.

---

*Generated by adapters/codex-cli/adapter.ps1 - do not edit manually.*
'@
    [System.IO.File]::WriteAllText($out, $content, [System.Text.Encoding]::UTF8)
}

function _Codex-TranslateCommands {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    foreach ($f in (Get-ChildItem $Src -Filter "*.md")) {
        if (-not (Should-Include $f.FullName $CODEX_PLATFORM)) { continue }
        $out = Join-Path $Dst $f.Name
        Copy-Item $f.FullName $out
        Rewrite-ToolNeutral   $out
        Rewrite-PlatformPaths $out $CODEX_DIR
    }
}

function _Codex-CopyReferences {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    Copy-Item "$Src\*" $Dst -Recurse -Force
    foreach ($f in (Get-ChildItem $Dst -Filter "*.md" -Recurse)) {
        Rewrite-PlatformPaths $f.FullName $CODEX_DIR
    }
}

function _Codex-CopyScripts {
    param([string]$Src, [string]$Dst)
    if (-not (Test-Path $Src)) { return }
    New-Item -ItemType Directory -Force $Dst | Out-Null
    Copy-Item "$Src\*" $Dst -Recurse -Force
}

function _Codex-EmitInstallHint {
    param([string]$Dst)
    $content = @'
# Install on Codex CLI

```powershell
# From the repo root, after running: pwsh -File scripts/build.ps1 --platform codex-cli
# Copy the built tree into your vault root:
Copy-Item "dist\codex-cli\*" "/path/to/your/vault/" -Recurse -Force
```

Then in your vault:

- `AGENTS.md` is the operating manual Codex reads at session start.
- `.codex/commands/*.md` are the command bodies the AI follows when a
  matching trigger fires.
- `.codex/scripts/` holds the Python helpers invoked by the research
  toolkit commands. Run them via `uv run -m scripts.research.<name>`.

Start Codex CLI from the vault root.
'@
    [System.IO.File]::WriteAllText((Join-Path $Dst 'INSTALL.md'), $content, [System.Text.Encoding]::UTF8)
}
